# Generated by Django 4.1.2 on 2022-10-12 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('profile_image', models.CharField(blank=True, max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(default=None, max_length=50)),
                ('year', models.IntegerField(default=None)),
                ('condition', models.CharField(default=None, max_length=50)),
                ('mileage', models.CharField(default=None, max_length=50)),
                ('accidents', models.BooleanField(default=False)),
                ('tickets', models.BooleanField(default=False)),
                ('premium', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('provider', models.CharField(default=None, max_length=50)),
                ('liability', models.CharField(default=None, max_length=50)),
                ('uninsured', models.CharField(default=None, max_length=50)),
                ('medical', models.IntegerField(default=None)),
                ('roadside', models.BooleanField(default=False)),
                ('rental', models.BooleanField(default=False)),
                ('safe_driver', models.BooleanField(default=False)),
                ('zip', models.CharField(default=None, max_length=5)),
                ('annual_miles', models.IntegerField(default=None)),
                ('credit_score', models.CharField(default=None, max_length=50)),
                ('age', models.IntegerField(default=None)),
                ('coverage_preference', models.CharField(default=None, max_length=50)),
                ('username', models.CharField(default=None, max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
