# Generated by Django 4.1.2 on 2022-10-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('mileage', models.CharField(max_length=50)),
                ('accidents', models.BooleanField(default=False)),
                ('tickets', models.BooleanField(default=False)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.CharField(max_length=50)),
                ('liability', models.CharField(max_length=50)),
                ('uninsured', models.CharField(max_length=50)),
                ('medical', models.CharField(max_length=50)),
                ('roadside', models.BooleanField(default=False)),
                ('rental', models.BooleanField(default=False)),
                ('safe_driver', models.BooleanField(default=False)),
                ('zip', models.IntegerField(max_length=5)),
                ('annual_miles', models.IntegerField(max_length=5)),
                ('credit_score', models.IntegerField(max_length=3)),
                ('age', models.IntegerField(max_length=3)),
                ('coverage_preference', models.CharField(max_length=30)),
            ],
        ),
    ]
