# Generated by Django 4.1.2 on 2022-10-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_bid_auto_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='auto_post_id',
            field=models.IntegerField(default=None),
        ),
    ]
