# Generated by Django 4.1.2 on 2022-10-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auto',
            name='annual_miles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auto',
            name='coverage_preference',
            field=models.CharField(choices=[('NO COVERAGE CHANGES', 'No coverage changes'), ('SIMILAR COVERAGE WITH MIOR ADJUSTMENTS', 'Similar coverage with minor adjustments'), ('OPEN TO ANY ADJUSTMENTS', 'Open to any adjustments')], default='NO COVERAGE CHANGES', max_length=100),
        ),
        migrations.AlterField(
            model_name='auto',
            name='credit_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auto',
            name='medical',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auto',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auto',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
