# Generated by Django 4.1.2 on 2022-10-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_auto_age_alter_auto_annual_miles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='accidents',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='auto',
            name='tickets',
            field=models.IntegerField(default=False),
        ),
    ]
