# Generated by Django 4.1.2 on 2022-10-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_auto_accidents_alter_auto_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='condition',
            field=models.CharField(choices=[('LIKE NEW', 'Like New'), ('MINOR COSMETIC ISSUES', 'Minor Cosmetic Issues'), ('MINOR MECHANICAL ISSUES', 'Minor Mechanical Issues'), ('MAJOR MECHANICAL ISSUES', 'Major Mechanical Issues')], default='LIKE NEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='auto',
            name='credit_score',
            field=models.CharField(choices=[('800+', '800+'), ('720-800', '720-800'), ('600-719', '600-719'), ('400-599', '400-599')], default='800+', max_length=10),
        ),
    ]
