# Generated by Django 4.1.2 on 2022-10-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_auto_condition_alter_auto_credit_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='accidents',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auto',
            name='tickets',
            field=models.BooleanField(default=False),
        ),
    ]
