# Generated by Django 4.1.2 on 2022-10-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_auto_accidents_alter_auto_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='condition',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auto',
            name='coverage_preference',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auto',
            name='credit_score',
            field=models.CharField(max_length=50),
        ),
    ]
