# Generated by Django 4.1.2 on 2022-10-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='accidents',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='age',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='annual_miles',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='coverage_preference',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='credit_score',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='liability',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='medical',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='model',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='premium',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='rental',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='roadside',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='safe_driver',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='uninsured',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='year',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='zip',
        ),
    ]
