# Generated by Django 4.1.2 on 2022-10-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_auto_accidents_remove_auto_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='user',
        ),
    ]
