# Generated by Django 4.1.2 on 2022-10-10 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0013_remove_auto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auto',
            name='vehicle_model',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
