# Generated by Django 4.1.2 on 2022-10-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_user_auto_vehicle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='condition',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='auto',
            name='year',
            field=models.IntegerField(default=None),
        ),
    ]
