# Generated by Django 4.1.2 on 2022-10-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_condition_auto_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='accidents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auto',
            name='liability',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='auto',
            name='mileage',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='auto',
            name='premium',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='auto',
            name='provider',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='auto',
            name='tickets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auto',
            name='uninsured',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
