# Generated by Django 4.1.2 on 2022-10-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_accidents_auto_liability_auto_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='auto',
            name='annual_miles',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='auto',
            name='coverage_preference',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='auto',
            name='credit_score',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='auto',
            name='medical',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='auto',
            name='rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auto',
            name='roadside',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auto',
            name='safe_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auto',
            name='zip',
            field=models.IntegerField(default=None),
        ),
    ]
