# Generated by Django 4.1.2 on 2022-10-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_age_auto_annual_miles_auto_coverage_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='age',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='annual_miles',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='coverage_preference',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='credit_score',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='safe_driver',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='zip',
        ),
    ]
