# Generated by Django 4.1.2 on 2022-10-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_auto_age_remove_auto_annual_miles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='medical',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='rental',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='roadside',
        ),
    ]
