# Generated by Django 4.1.2 on 2022-10-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_remove_auto_medical_remove_auto_rental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='medical',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='auto',
            name='roadside',
            field=models.BooleanField(default=False),
        ),
    ]
