# Generated by Django 4.1.2 on 2022-10-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_medical_auto_roadside'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='annual_miles',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='auto',
            name='rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auto',
            name='safe_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auto',
            name='zip',
            field=models.IntegerField(default=None),
        ),
    ]
