# Generated by Django 4.1.2 on 2022-10-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_annual_miles_auto_rental_auto_safe_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='auto',
            name='coverage_preference',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='auto',
            name='credit_score',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
