# Generated by Django 4.1.2 on 2022-10-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_age_auto_coverage_preference_auto_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
