# Generated by Django 4.1.2 on 2022-10-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
