# Generated by Django 4.1.2 on 2022-10-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_delete_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='zip',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
