# Generated by Django 4.1.2 on 2022-10-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_alter_auto_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bidder',
            field=models.BooleanField(default=False),
        ),
    ]
